Prologicielsucces/urls.py
from django.contrib import admin
from django.urls import path
from finances import views
from accounts.views import login_user,logout_user


urlpatterns = [
    path('candidates/', views.CandidateListView.as_view(), name='candidate_list'),
    
    path("admin/", admin.site.urls),
    path('accounts/', login_user, name='login'),
    path('accounts/log', logout_user, name='signup'),
    path('administration/menu', views.menu, name='menu'),
    path('actionnaire/menu', views.afficher_dashboard, name='menuact'),

    
# URL pour la liste des genres
    path('genres/', views.liste_genres, name='liste_genres'),
    # URL pour ajouter un genre
    path('genres/ajouter/', views.creer_genre, name='ajouter_genre'),
    # URL pour modifier un genre
    path('genres/modifier/<int:pk>/', views.modifier_genre, name='modifier_genre'),
    # URL pour supprimer un genre
    path('genres/supprimer/<int:pk>/', views.supprimer_genre, name='supprimer_genre'),
    
    # URL pour la liste des matrimoniales
    path('matrimoniales/', views.liste_matrimoniales, name='liste_matrimoniales'),
    # URL pour ajouter une matrimoniales
    path('matrimoniales/ajouter/', views.creer_matrimoniale, name='ajouter_matrimoniales'),
    # URL pour modifier une matrimoniales
    path('matrimoniales/modifier/<int:pk>/', views.modifier_matrimoniale, name='modifier_matrimoniales'),
    # URL pour supprimer une matrimoniales
    path('matrimoniales/supprimer/<int:pk>/', views.supprimer_matrimoniale, name='supprimer_matrimoniales'),
    
    # URL pour la liste des types de prêts
    path('typeprets/', views.liste_typeprets, name='liste_typeprets'),
    # URL pour ajouter un type de prêt
    path('typeprets/ajouter/', views.creer_typepret, name='ajouter_typeprets'),
    # URL pour modifier un type de prêt
    path('typeprets/modifier/<int:pk>/', views.modifier_typepret, name='modifier_typeprets'),
    # URL pour supprimer un type de prêt
    path('typeprets/supprimer/<int:pk>/', views.supprimer_typepret, name='supprimer_typeprets'),
# URL pour la liste des clients
    path('clients/', views.liste_clients, name='liste_clients'),
    path('clients/<int:client_id>/detail', views.detail_clients, name='detail_clients'),
    # URL pour ajouter un client
    path('clients/ajouter/', views.creer_client, name='ajouter_client'),
    # URL pour modifier un client
    path('clients/modifier/<int:pk>/', views.modifier_client, name='modifier_client'),
    # URL pour supprimer un client
    path('clients/supprimer/<int:pk>/', views.supprimer_client, name='supprimer_client'),
    
    # URL pour la liste des comptes épargnes
    path('comptes_epargnes/', views.liste_comptes_epargne, name='liste_comptes_epargnes'),
    path('comptes_epargne/<int:compte_epargne_id>/', views.detail_compte_epargne, name='detail_compte_epargne'),
    # URL pour ajouter un compte épargne
    path('comptes_epargnes/ajouter/', views.creer_compte_epargne, name='ajouter_compte_epargne'),
    # URL pour modifier un compte épargne
    path('comptes_epargnes/modifier/<int:pk>/', views.modifier_compte_epargne, name='modifier_compte_epargne'),
    # URL pour supprimer un compte épargne
    path('comptes_epargnes/supprimer/<int:pk>/', views.supprimer_compte_epargne, name='supprimer_compte_epargne'),
    
    # URL pour la liste des comptes prêts
    path('comptes_prets/', views.liste_comptes_prets, name='liste_comptes_prets'),
    path('compte_pret/<int:compte_pret_id>/', views.detail_compte_pret, name='detail_compte_pret'),
    # URL pour la liste des comptes prêts
    path('comptes_prets/echeances', views.clients_proche_echeance, name='clients_proche_echeance'),
    # URL pour la liste des comptes prêts
    path('comptes_prets/echeancesnon', views.liste_echeances_non_payees, name='liste_echeances_non_payees'),
    # URL pour ajouter un compte prêt
    path('comptes_prets/<int:client_id>/ajouter/', views.ajouter_compte_pret, name='ajouter_compte_pret'),
    # URL pour modifier un compte prêt
    path('comptes_prets/modifier/<int:pk>/', views.modifier_compte_pret, name='modifier_compte_pret'),
    # URL pour supprimer un compte prêt
    path('comptes_prets/supprimer/<int:pk>/', views.supprimer_compte_pret, name='supprimer_compte_pret'),
    path('comptes_prets/modifier/<int:pk>/', views.modifier_compte_pret, name='modifier_compte_pret'),
    # URL pour la liste des agents
    path('agents/', views.liste_agents, name='liste_agents'),
    # URL pour ajouter un agent
    path('agents/ajouter/', views.ajouter_agent, name='ajouter_agent'),
    # URL pour modifier un agent
    path('agents/modifier/<int:pk>/', views.modifier_agent, name='modifier_agent'),
    # URL pour supprimer un agent
    path('agents/supprimer/<int:pk>/', views.supprimer_agent, name='supprimer_agent'),
    path('modifier_est_paye/<int:actionnaire_id>/', views.modifier_est_paye, name='modifier_est_paye'),
    path('modifier_est_payeretard/<int:actionnaire_id>/', views.modifier_est_payere, name='modifier_est_payere'),

    # URL pour la liste des transactions
    path('creer_transaction_epargne/<int:id>', views.creer_transaction_epargne, name='creer_transaction_epargne'),
    path('creer_transaction_pret/', views.creer_transaction_pret, name='creer_transaction_pret'),
    path('modifier_transaction_epargne/<int:pk>/', views.modifier_transaction_epargne, name='modifier_transaction_epargne'),
    path('modifier_transaction_pret/<int:pk>/', views.modifier_transaction_pret, name='modifier_transaction_pret'),
    path('supprimer_transaction/<int:pk>/', views.supprimer_transactionEpargne, name='supprimer_transaction'),
    path('liste_transactions/', views.liste_transactions, name='liste_transactions'),

    # URL pour la liste des depenses
    path('liste_depenses/', views.liste_depenses, name='liste_depenses'),
    path('ajouter_depense/', views.ajouter_depense, name='ajouter_depense'),
    path('modifier_depense/<int:depense_id>/', views.modifier_depense, name='modifier_depense'),
    path('supprimer_depense/<int:depense_id>/', views.supprimer_depense, name='supprimer_depense'),

    # URL pour la liste des actionnaires
    path('resultats/', views.afficher_resultats, name='afficher_resultats'),
    path('actionnaires/', views.liste_actionnaires, name='liste_actionnaires'),
    path('detail_actionnaire/<int:actionnaire_id>/', views.detail_actionnaire, name='detail_actionnaire'),
    path('actionnaires/ajouter/', views.ajouter_actionnaire, name='ajouter_actionnaire'),
    path('actionnaires/modifier/<int:actionnaire_id>/', views.modifier_actionnaire, name='modifier_actionnaire'),
    path('actionnaires/supprimer/<int:actionnaire_id>/', views.supprimer_actionnaire, name='supprimer_actionnaire'),
    path('courbe_transactions/', views.courbe_transactions, name='courbe_transactions'),
]

finances/models.py
from datetime import timezone
from django.db import models
from django.db.models import Count, Q,Sum
from accounts.models import Utilisateurs


class Genres(models.Model):
    sexe = models.CharField(max_length=10)
    def __str__(self):
        return f'{self.sexe}'

class Matrimoniales(models.Model):
    matrimoniale = models.CharField(max_length=50)
    def __str__(self):
        return f'{self.matrimoniale}'
    
class Typeprets(models.Model):
    type_pret = models.CharField(max_length=50,null=False)
    def __str__(self):
        return f'{self.type_pret}'

class Statuts(models.Model):
    statut = models.CharField(max_length=50,null=False)
    def __str__(self):
        return f'{self.statut}'

class Clients(models.Model):
    TYPE_PIECE_CHOICES = [
        ('CNI', 'Carte Nationale d\'Identité'),
        ('passeport', 'Passeport'),
        ('Attestation', 'Attestation d\'identité'),
    ]
    nom = models.CharField(max_length=100, null=True)
    prenom = models.CharField(max_length=100, null=True)
    adresse = models.CharField(max_length=200, null=True)
    telephone = models.CharField(max_length=20, null=True)
    sexe = models.ForeignKey(Genres, on_delete=models.CASCADE, null=True)
    statut = models.ForeignKey(Statuts, on_delete=models.CASCADE, null=True)
    email = models.EmailField(unique=True, null=True)
    date_inscription = models.DateField(auto_now_add=True, null=True)
    photo = models.ImageField(upload_to='Images/Photos/Clients/', blank=True, null=True)
    piece_identite_scan = models.ImageField(upload_to='Images/Photos/Clients/Pieceidentite/', blank=True, null=True)
    profession = models.CharField(max_length=100, blank=True, null=True)
    date_naissance = models.DateField()
    lieu_naissance = models.CharField(max_length=100, null=True)
    type_piece_identite = models.CharField(max_length=20, choices=TYPE_PIECE_CHOICES)
    numero_piece_identite = models.CharField(max_length=100, null=True)
    validite_piece_identite_debut = models.DateField()
    validite_piece_identite_fin = models.DateField()
    ville_village = models.CharField(max_length=100, null=True)
    matrimoniale = models.ForeignKey(Matrimoniales, on_delete=models.CASCADE,null=True)
    

    def __str__(self):
        return f"{self.prenom} {self.nom}"
    
class CompteEpargnes(models.Model):
    client = models.ForeignKey(Clients, on_delete=models.CASCADE, null=True)
    numero_compte = models.CharField(max_length=20, unique=True)
    solde = models.DecimalField(max_digits=10, decimal_places=2, default=0) # type: ignore
    statut = models.ForeignKey(Statuts, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Compte épargne {self.numero_compte} - {self.client}"
    
class ComptePrets(models.Model):
    client = models.ForeignKey(Clients, on_delete=models.CASCADE, null=True)
    numero_compte = models.CharField(max_length=20, unique=True)
    solde = models.DecimalField(max_digits=10, decimal_places=2, default=0) # type: ignore
    taux_interet = models.DecimalField(max_digits=5, decimal_places=2, default=1)  # type: ignore # 1% par mois
    duree_en_mois = models.PositiveIntegerField(default=12)
    date_debut_pret = models.DateField()
    

    date_fin_pret = models.DateField()
    somme_initiale = models.DecimalField(max_digits=10, decimal_places=2)
    domicile_bancaire = models.CharField(max_length=200, null=True)
    type_pret = models.ForeignKey(Typeprets, on_delete=models.CASCADE, null=True)
    date_demande = models.DateField(auto_now_add=True, null=True)
    statut = models.ForeignKey(Statuts, on_delete=models.CASCADE)

    def calculer_interets(self):
        # Calculez les intérêts en fonction de la durée du prêt
        # Vous pouvez ajouter le code ici pour effectuer le calcul des intérêts
        # Assurez-vous d'utiliser la durée en mois et le taux d'intérêt du prêt
        # Pour cet exemple, supposons que le taux d'intérêt est exprimé en pourcentage (1% par mois)
        return self.solde * (self.taux_interet / 100) * self.duree_en_mois

    def __str__(self):
        return f"Compte prêt {self.numero_compte} - {self.client}"
    
class Agent(models.Model):
    user = models.OneToOneField(Utilisateurs, on_delete=models.CASCADE)
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    adresse = models.CharField(max_length=200)
    telephone = models.CharField(max_length=20)
    email = models.EmailField(unique=True)

    def __str__(self):
        return f"{self.prenom} {self.nom}"
    
class Actionnaire(models.Model):
    user = models.OneToOneField(Utilisateurs, on_delete=models.CASCADE)
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    adresse = models.CharField(max_length=200)
    telephone = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    apport = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    pourcentage = models.DecimalField(max_digits=5, decimal_places=2,null=True)

    def __str__(self):
        return f"{self.prenom} {self.nom}"
    
class Echeancier(models.Model):
    compte_pret = models.ForeignKey(ComptePrets, on_delete=models.CASCADE)
    date_echeance = models.DateField()
    montant_echeance = models.DecimalField(max_digits=10, decimal_places=2)
    montant_interet = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    est_paye = models.BooleanField(default=False)

    def __str__(self):
        return f"Échéance pour le compte prêt {self.compte_pret.numero_compte} - Montant: {self.montant_echeance}"


class TransactionEpargne(models.Model):
    TYPE_CHOICES = [
        ('Depot', 'Dépôt'),
        ('Retrait', 'Retrait'),
        ('Virement', 'Virement'),
    ]

    compte_epargne = models.ForeignKey(
        CompteEpargnes,
        on_delete=models.CASCADE,
        related_name='transactions_epargne',
        null=True,
        blank=True
    )

    montant = models.DecimalField(max_digits=10, decimal_places=2)
    type_transaction = models.CharField(max_length=20, choices=TYPE_CHOICES)
    date_transaction = models.DateTimeField(auto_now_add=True)
    agent = models.ForeignKey(Agent, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        if self.type_transaction == 'Virement':
            return f"{self.type_transaction} de {self.montant} FCFA de {self.compte_epargne} à {self.compte_pret}"
        else:
            return f"{self.type_transaction} de {self.montant} FCFA sur le compte {self.compte_epargne}"


class TransactionPret(models.Model):
    TYPE_CHOICES = [
        ('Depot', 'Dépôt'),
        ('Retrait', 'Retrait'),
        ('Virement', 'Virement'),
    ]

    compte_pret = models.ForeignKey(
        ComptePrets,
        on_delete=models.CASCADE,
        related_name='transactions_pret',
        null=True,
        blank=True
    )

    montant = models.DecimalField(max_digits=10, decimal_places=2)
    type_transaction = models.CharField(max_length=20, choices=TYPE_CHOICES)
    date_transaction = models.DateTimeField(auto_now_add=True)
    agent = models.ForeignKey(Utilisateurs, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        if self.type_transaction == 'Virement':
            return f"{self.type_transaction} de {self.montant} FCFA de {self.compte_pret} à {self.compte_epargne}"
        else:
            return f"{self.type_transaction} de {self.montant} FCFA sur le compte {self.compte_pret}"

class Depense(models.Model):
    nom = models.CharField(max_length=100)
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    agent = models.ForeignKey(Agent, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.nom
    
class License(models.Model):
    client_name = models.CharField(max_length=100)
    license_key = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def calculate_valid_until(self):
        # Calculer la date d'expiration en ajoutant un an à la date de création
        return self.created_at + timezone.timedelta(days=365)

    def is_valid(self):
        return timezone.now() <= self.calculate_valid_until()

finances/templates/Pages/Comptepret/ajouter_compte_pret.html
{% extends 'Base/base.html' %}

{% block content %}
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0 font-size-18">KHAGest</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{% url 'liste_comptes_prets' %}">Comptes de Prêts</a></li>
                        <li class="breadcrumb-item active">Ajouter un Compte de Prêt</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12"> 
            <div class="card">
                <div class="card-body">
                    {% if etud %}
                    <h4 class="card-title mb-4">Formulaire d'Ajout de Compte de Prêt / <span class="badge badge-pill badge-soft-danger font-size-11">{{ etud.0.nom }} {{ etud.0.prenom }}</span></h4>
                    {% endif %}

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group" hidden>
                            <label for="id_client">Client</label>
                            {{ form.client }}
                        </div>
                        <div class="form-group" hidden>
                            <label for="id_taux_interet">Taux d'Intérêt</label>
                            {{ form.taux_interet }}
                        </div>

                        <div class="row">
                            <div class="col-md-8">
                                <div class="mb-3">
                                    <label for="formrow-email-input" class="form-label">Type pret</label>
                                    {{ form.type_pret }}
                                </div> 
                            </div>
                            <div class="col-md-2">
                                <div class="mb-3">
                                    <label for="formrow-email-input" class="form-label">Durée en Mois</label>
                                    {{ form.duree_en_mois }}
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="mb-3">
                                    <label for="formrow-email-input" class="form-label">Date de Début de Prêt</label>
                                    {{ form.date_debut_pret }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <div class="mb-3">
                                    <label for="id_somme_initiale" class="form-label">Somme Initiale</label>
                                    {{ form.somme_initiale }}
                                </div>
                            </div>
                            
                            
                            <div class="col-md-10">
                                <div class="mb-3">
                                    <label for="formrow-email-input" class="form-label">Domicile Bancaire</label>
                                    {{ form.domicile_bancaire }}
                                </div>
                            </div>
                        </div>

                        

                         

                        

                        
                        <div class="mt-4 hstack gap-2">
                            <button type="submit" class="btn btn-soft-success w-100" >Valider</button>
                            <a class="btn btn-soft-primary w-100" href="{% url 'liste_comptes_prets' %}">Retour en Arrière</a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <script>
        function updateDateFin() {
            const dateDebutPret = new Date(document.getElementById('id_date_debut_pret').value);
            const dureeEnMois = parseInt(document.getElementById('id_duree_en_mois').value);
            const dateFinPret = new Date(dateDebutPret);
            dateFinPret.setMonth(dateDebutPret.getMonth() + dureeEnMois);
            document.getElementById('id_date_fin_pret').valueAsDate = dateFinPret;
        }

        updateDateFin();
        document.getElementById('id_duree_en_mois').addEventListener('input', updateDateFin);
    </script>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const sommeInitialeInput = document.getElementById('id_somme_initiale');
                const submitBtn = document.getElementById('submitBtn');
            
                sommeInitialeInput.addEventListener('input', function() {
                    const sommeInitialeValue = parseFloat(sommeInitialeInput.value);
                    if (isNaN(sommeInitialeValue) || sommeInitialeValue <= 0) {
                        submitBtn.disabled = true;
                    } else {
                        submitBtn.disabled = false;
                    }
                });
            });
            </script>
            
        
    
{% endblock content %}

finances/templates/Pages/Comptepret/detail_compte_pret.html
{% extends 'Base/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">Détails du Compte Prêt</h4>
            <div class="page-title-right">
                <a href="{% url 'liste_comptes_prets' %}" class="btn btn-primary">Retour à la liste</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Informations sur le Compte Prêt</h5>
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <th>Numéro de Compte</th>
                            <td>{{ compte_pret.numero_compte }}</td>
                        </tr>
                        <tr>
                            <th>Client</th>
                            <td>{{ compte_pret.client }}</td>
                        </tr>
                        <tr>
                            <th>Solde</th>
                            <td>{{ compte_pret.solde }}</td>
                        </tr>
                        <tr>
                            <th>Date de Début</th>
                            <td>{{ compte_pret.date_debut_pret }}</td>
                        </tr>
                        <tr>
                            <th>Date de Fin</th>
                            <td>{{ compte_pret.date_fin_pret }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Échéanciers associés</h5>
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Date d'Échéance</th>
                            <th>Montant de l'Échéance</th>
                            <th>Est Payé</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for echeancier in echeanciers %}
                        <tr>
                            <td>{{ echeancier.date_echeance }}</td>
                            <td>{{ echeancier.montant_echeance }}</td>
                            <td>{% if echeancier.est_paye %}Oui{% else %}Non{% endif %}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

finances/templates/Pages/Comptepret/liste_comptes_prets.html
{% extends 'Base/base.html' %}

{% block content %}
 
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">KHAGest</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'menu' %}">Accueil</a></li>
                    <li class="breadcrumb-item active">Liste des comptes prets</li>
                </ol>
            </div> 
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
               
                <div class="row">
                    <div class="col-6 d-flex align-items-center">
                        <h4 class="mb-sm-0 font-size-18">Liste des Comptes Prêts</h4>
                    </div>
                    
                </div><br><br>
                    <table id="datatable-buttons" class="table table-bordered dt-responsive nowrap w-100">
                        <thead class="table-light">
                            <tr>
                                <th>Numéro de Compte</th>
                                <th>Client</th>
                                <th>Solde</th>
                                <th>Date de Début</th>
                                <th>Date de Fin</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for compte in comptes_prets %}
                            <tr>
                                <td>{{ compte.numero_compte }}</td>
                                <td>{{ compte.client }}</td>
                                <td>{{ compte.solde }}</td>
                                <td>{{ compte.date_debut_pret }}</td>
                                <td>{{ compte.date_fin_pret }}</td>
                                
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-secondary btn-sm" type="button">
                                            Actions
                                        </button>
                                        <button type="button" class="btn btn-sm btn-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                                            <iconify-icon icon="mdi:chevron-down-circle"></iconify-icon>
                                        </button>
                                        <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'detail_compte_pret' compte.id %}" >Détails</a>
                                    {% if user.is_authenticated %}
                                    {% if user.role == 'ADMINISTRATEUR' or user.role == 'ADMINISTRATEURSUPER' %}
                                    <a class="dropdown-item" href="{% url 'modifier_compte_pret' compte.id %}" >Modifier</a>
                                    <a class="dropdown-item" href="{% url 'supprimer_compte_pret' compte.id %}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce compte prêt ?')">Supprimer</a>
                                    {% endif %}
                                    {% endif %}
                                        </div>
                                    </div>
                                    
                                </td>
                            
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="6">Aucune donnée disponible.</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    
</div>
{% endblock content %}

finances/templates/Pages/Comptepret/listeecheance.html
{% extends 'Base/base.html' %}

{% block content %}
 <!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">KHAGest</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'menu' %}">Institutions</a></li>
                    <li class="breadcrumb-item active">Niveau d'études</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <div class="row">
                    <div class="col-6 d-flex align-items-center">
                      <h6 class="mb-0">Consulter la liste des Niveaux d'études</h6>
                    </div>
                    <div class="col-6 text-end">
                      
                    </div>
                  </div><br><br>
                  <table id="datatable-buttons" class="table table-bordered dt-responsive nowrap w-100">
                    <thead class="table-light">
                        <tr>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Téléphone</th>
                            <th>Numéro de compte prêt</th>
                            <th>Taches</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for client in clients %}
                        <tr>
                            <td>{{ client.compte_pret__client__nom }}</td>
                            <td>{{ client.compte_pret__client__prenom }}</td>
                            <td>{{ client.compte_pret__client__telephone }}</td>
                            <td>{{ client.compte_pret__numero_compte }}</td>
                            <td>
                                <form method="post" action="{% url 'modifier_est_paye' client.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-success" onclick="return confirm('Êtes-vous sûr de vouloir marquer cette échéance comme payée ?')">Marquer comme payé</button>
                                </form>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4">Aucune donnée disponible.</td>
                        </tr>
                        {% endfor %} 
                    </tbody>
                </table>
                


</div>
</div>
</div> <!-- end col -->
</div> <!-- end row -->
{% endblock content %}